// ══════════════════════════════════════════
// BOOKING PLATFORM — Mock Data
// ══════════════════════════════════════════

export interface Service {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  thumbnail: string;
  images: string[];
  category: string;
  location: string;
  priceFrom: number;
  priceTo?: number;
  priceUnit: string;
  rating: number;
  reviewCount: number;
  amenities: string[];
  tags: string[];
  host: string;
  hostAvatar: string;
  isInstantBook?: boolean;
  isFeatured?: boolean;
  availableSlots: TimeSlot[];
}

export interface TimeSlot {
  date: string;
  times: string[];
}

export interface Booking {
  id: string;
  serviceId: string;
  name: string;
  email: string;
  phone: string;
  date: string;
  time: string;
  guests: number;
  notes: string;
  status: 'pending' | 'confirmed' | 'cancelled';
  totalPrice: number;
}

export const BOOKING_CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: '🏠' },
  { id: 'hotel', label: 'Khách sạn', icon: '🏨' },
  { id: 'restaurant', label: 'Nhà hàng', icon: '🍽️' },
  { id: 'spa', label: 'Spa & Wellness', icon: '💆' },
  { id: 'tour', label: 'Tour du lịch', icon: '🗺️' },
  { id: 'experience', label: 'Trải nghiệm', icon: '🌟' },
  { id: 'event', label: 'Sự kiện', icon: '🎉' },
  { id: 'sports', label: 'Thể thao', icon: '⚽' },
];

export const SERVICES: Service[] = [
  {
    id: 's1',
    slug: 'villa-da-lat-pine-view',
    title: 'Pine View Villa Đà Lạt',
    subtitle: 'Villa thông 4 phòng ngủ, view thung lũng tuyệt đẹp',
    description: 'Villa sang trọng giữa rừng thông Đà Lạt. 4 phòng ngủ, hồ bơi nước nóng, view toàn cảnh thung lũng. Hoàn hảo cho gia đình và nhóm bạn.',
    thumbnail: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    category: 'hotel',
    location: 'Đà Lạt, Lâm Đồng',
    priceFrom: 3500000,
    priceTo: 5000000,
    priceUnit: '/đêm',
    rating: 4.95,
    reviewCount: 234,
    amenities: ['Hồ bơi', 'WiFi', 'Bếp đầy đủ', 'BBQ', 'Lò sưởi', 'Bãi đỗ xe', 'View núi'],
    tags: ['Villa', 'Đà Lạt', 'Gia đình', 'Thư giãn'],
    host: 'Nguyễn Gia Hào',
    hostAvatar: 'https://i.pravatar.cc/150?img=18',
    isInstantBook: true,
    isFeatured: true,
    availableSlots: [
      { date: '2025-07-05', times: ['14:00'] },
      { date: '2025-07-06', times: ['14:00'] },
      { date: '2025-07-10', times: ['14:00'] },
    ],
  },
  {
    id: 's2',
    slug: 'restaurant-pho-ba-hang',
    title: 'Phở Bà Hàng — Fine Dining',
    subtitle: 'Trải nghiệm ẩm thực Việt truyền thống theo phong cách hiện đại',
    description: 'Nhà hàng fine dining với thực đơn Việt Nam truyền thống được nâng cấp. Không gian ấm cúng, phục vụ chu đáo. Đặt bàn trước để được trải nghiệm tốt nhất.',
    thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    ],
    category: 'restaurant',
    location: 'Hoàn Kiếm, Hà Nội',
    priceFrom: 350000,
    priceUnit: '/người',
    rating: 4.8,
    reviewCount: 567,
    amenities: ['Không gian riêng', 'Rượu vang', 'Menu cố định', 'Parking', 'WiFi'],
    tags: ['Fine Dining', 'Việt Nam', 'Hà Nội', 'Lãng mạn'],
    host: 'Chef Trần Thị Bà Hàng',
    hostAvatar: 'https://i.pravatar.cc/150?img=29',
    isFeatured: true,
    availableSlots: [
      { date: '2025-07-03', times: ['18:00', '19:00', '20:00'] },
      { date: '2025-07-04', times: ['11:30', '12:00', '18:00', '19:00'] },
      { date: '2025-07-05', times: ['18:00', '19:30'] },
    ],
  },
  {
    id: 's3',
    slug: 'spa-zen-garden-hoi-an',
    title: 'Zen Garden Spa — Hội An',
    subtitle: 'Spa truyền thống Việt giữa lòng phố cổ Hội An',
    description: 'Trải nghiệm spa truyền thống Việt Nam với các liệu pháp thảo dược địa phương. Không gian tĩnh lặng, thanh thản giữa lòng phố cổ.',
    thumbnail: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    ],
    category: 'spa',
    location: 'Hội An, Quảng Nam',
    priceFrom: 450000,
    priceUnit: '/người/buổi',
    rating: 4.9,
    reviewCount: 892,
    amenities: ['Massage', 'Tắm thảo dược', 'Đá nóng', 'Trà thảo mộc', 'Thay đồ riêng'],
    tags: ['Spa', 'Wellness', 'Hội An', 'Thư giãn'],
    host: 'Võ Thị Lan Hương',
    hostAvatar: 'https://i.pravatar.cc/150?img=38',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-03', times: ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00'] },
      { date: '2025-07-04', times: ['09:00', '10:30', '14:00', '15:30'] },
    ],
  },
  {
    id: 's4',
    slug: 'tour-ha-long-2n1d',
    title: 'Tour Hạ Long 2N1Đ — Thuyền Luxury',
    subtitle: 'Cruise 5 sao khám phá vịnh Hạ Long huyền bí',
    description: 'Tour cruise 2 ngày 1 đêm trên du thuyền 5 sao. Thăm hang động, chèo kayak, xem mặt trời mọc trên vịnh. Bao gồm toàn bộ bữa ăn và hoạt động.',
    thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    ],
    category: 'tour',
    location: 'Hạ Long, Quảng Ninh',
    priceFrom: 2800000,
    priceUnit: '/người',
    rating: 4.85,
    reviewCount: 1240,
    amenities: ['Cabin riêng', 'Kayak', 'Lặn ngắm san hô', 'Bữa ăn 5 sao', 'Hướng dẫn viên', 'Bảo hiểm'],
    tags: ['Hạ Long', 'Cruise', 'Tour', 'Thiên nhiên'],
    host: 'Hạ Long Discovery Tours',
    hostAvatar: 'https://i.pravatar.cc/150?img=48',
    isFeatured: true,
    availableSlots: [
      { date: '2025-07-05', times: ['07:30'] },
      { date: '2025-07-08', times: ['07:30'] },
      { date: '2025-07-12', times: ['07:30'] },
    ],
  },
  {
    id: 's5',
    slug: 'tennis-court-sky-sports',
    title: 'Sky Sports Complex — Sân tennis mái vòm',
    subtitle: '4 sân tennis tiêu chuẩn ATP trong nhà, có HLV',
    description: 'Phức hợp thể thao hiện đại với 4 sân tennis trong nhà, có điều hòa. Đặt sân theo giờ, có HLV cá nhân theo yêu cầu.',
    thumbnail: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80'],
    category: 'sports',
    location: 'Cầu Giấy, Hà Nội',
    priceFrom: 200000,
    priceUnit: '/giờ/sân',
    rating: 4.7,
    reviewCount: 445,
    amenities: ['Phòng thay đồ', 'Giữ vợt', 'Thuê vợt', 'Nước miễn phí', 'Điều hòa', 'Camera'],
    tags: ['Tennis', 'Thể thao', 'Hà Nội', 'Trong nhà'],
    host: 'Sky Sports Management',
    hostAvatar: 'https://i.pravatar.cc/150?img=58',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-03', times: ['06:00', '07:00', '08:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'] },
      { date: '2025-07-04', times: ['06:00', '07:00', '17:00', '18:00', '19:00', '20:00'] },
    ],
  },
  {
    id: 's6',
    slug: 'event-rooftop-birthday',
    title: 'The Rooftop — Venue Tiệc trên cao',
    subtitle: 'Không gian tổ chức sự kiện 360° view Hồ Chí Minh city',
    description: 'Venue rooftop độc quyền tầng 40, sức chứa 150 khách. Phù hợp sinh nhật, tiệc cưới nhỏ, team building, ra mắt sản phẩm. Bao gồm setup và catering.',
    thumbnail: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80'],
    category: 'event',
    location: 'Quận 1, TP. Hồ Chí Minh',
    priceFrom: 15000000,
    priceUnit: '/buổi',
    rating: 4.9,
    reviewCount: 128,
    amenities: ['Bar', 'DJ Setup', 'Âm thanh ánh sáng', 'Catering', 'Photo booth', 'Bãi đỗ xe VIP'],
    tags: ['Sự kiện', 'Rooftop', 'HCM', 'Tiệc'],
    host: 'The Rooftop Events',
    hostAvatar: 'https://i.pravatar.cc/150?img=68',
    availableSlots: [
      { date: '2025-07-06', times: ['18:00'] },
      { date: '2025-07-13', times: ['18:00'] },
      { date: '2025-07-20', times: ['18:00'] },
    ],
  },
  // ── New services ───────────────────────────────────────────────────
  {
    id: 's7',
    slug: 'beachfront-resort-danang',
    title: 'Danang Pearl Resort & Spa',
    subtitle: 'Resort 5 sao trực tiếp bãi biển Mỹ Khê',
    description: 'Resort sang trọng với 120 phòng view biển, 3 hồ bơi vô cực, spa cao cấp và nhà hàng hải sản tươi sống. Bãi biển riêng dài 300m.',
    thumbnail: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80'],
    category: 'hotel',
    location: 'Đà Nẵng',
    priceFrom: 2200000,
    priceTo: 8000000,
    priceUnit: '/đêm',
    rating: 4.88,
    reviewCount: 1520,
    amenities: ['Bãi biển riêng', 'Hồ bơi vô cực', 'Spa', 'Gym', 'Nhà hàng', 'Bar', 'WiFi', 'Bãi đỗ xe'],
    tags: ['Resort', 'Đà Nẵng', 'Biển', '5 sao'],
    host: 'Danang Pearl Resort',
    hostAvatar: 'https://i.pravatar.cc/150?img=12',
    isInstantBook: true,
    isFeatured: true,
    availableSlots: [
      { date: '2025-07-07', times: ['14:00'] },
      { date: '2025-07-14', times: ['14:00'] },
    ],
  },
  {
    id: 's8',
    slug: 'nha-hang-quan-bun-bo-hue',
    title: 'Bún Bò Cô Ba — Đặc sản Huế',
    subtitle: 'Nhà hàng ẩm thực Huế truyền thống, không gian cung đình',
    description: 'Trải nghiệm ẩm thực cung đình Huế đích thực. Thực đơn gồm bún bò Huế, bánh bèo, cơm hến, nem lụi. Không gian được thiết kế theo phong cách nhà rường Huế cổ.',
    thumbnail: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80'],
    category: 'restaurant',
    location: 'Thành phố Huế',
    priceFrom: 180000,
    priceUnit: '/người',
    rating: 4.75,
    reviewCount: 890,
    amenities: ['Không gian cung đình', 'Khu vực riêng', 'Live nhạc dân tộc', 'Parking'],
    tags: ['Huế', 'Ẩm thực', 'Truyền thống', 'Cung đình'],
    host: 'Cô Ba Huế',
    hostAvatar: 'https://i.pravatar.cc/150?img=22',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-03', times: ['11:00', '12:00', '18:00', '19:00', '20:00'] },
      { date: '2025-07-04', times: ['11:30', '18:00', '19:30'] },
    ],
  },
  {
    id: 's9',
    slug: 'yoga-retreat-mui-ne',
    title: 'Mũi Né Yoga & Wellness Retreat',
    subtitle: 'Khóa tu dưỡng yoga 3 ngày 2 đêm bên bờ biển',
    description: 'Chương trình wellness toàn diện: yoga buổi sáng, thiền định, detox meal plan và massage thư giãn. Thầy giáo quốc tế, không gian hướng ra biển.',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80'],
    category: 'spa',
    location: 'Mũi Né, Bình Thuận',
    priceFrom: 3200000,
    priceUnit: '/người/3 ngày',
    rating: 4.93,
    reviewCount: 312,
    amenities: ['Yoga studio', 'Detox meals', 'Massage', 'Phòng riêng', 'Bãi biển riêng', 'Thiền định'],
    tags: ['Yoga', 'Wellness', 'Mũi Né', 'Retreat'],
    host: 'Guru Ananda',
    hostAvatar: 'https://i.pravatar.cc/150?img=32',
    availableSlots: [
      { date: '2025-07-07', times: ['08:00'] },
      { date: '2025-07-14', times: ['08:00'] },
      { date: '2025-07-21', times: ['08:00'] },
    ],
  },
  {
    id: 's10',
    slug: 'tour-sapa-trekking',
    title: 'Sapa Trekking — Bản Cát Cát & Fansipan',
    subtitle: 'Khám phá ruộng bậc thang và đỉnh Fansipan huyền thoại',
    description: 'Tour trekking 3 ngày: thăm bản Cát Cát, đi cáp treo lên đỉnh Fansipan 3.143m, trải nghiệm ẩm thực H\'Mông. Nghỉ tại homestay bản địa.',
    thumbnail: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80'],
    category: 'tour',
    location: 'Sapa, Lào Cai',
    priceFrom: 1800000,
    priceUnit: '/người/3 ngày',
    rating: 4.82,
    reviewCount: 2100,
    amenities: ['Homestay', 'Hướng dẫn viên H\'Mông', 'Cáp treo Fansipan', 'Bữa ăn địa phương', 'Xe đưa đón'],
    tags: ['Sapa', 'Trekking', 'Fansipan', 'Núi'],
    host: 'Sapa Adventure Team',
    hostAvatar: 'https://i.pravatar.cc/150?img=42',
    isFeatured: true,
    availableSlots: [
      { date: '2025-07-05', times: ['06:00'] },
      { date: '2025-07-09', times: ['06:00'] },
      { date: '2025-07-15', times: ['06:00'] },
    ],
  },
  {
    id: 's11',
    slug: 'golf-course-long-thanh',
    title: 'Long Thành Golf Club — Championship Course',
    subtitle: '36 lỗ chuẩn quốc tế, cảnh quan tuyệt đẹp',
    description: 'Sân golf 36 lỗ thiết kế bởi IMG, đạt tiêu chuẩn thi đấu quốc tế. Caddy chuyên nghiệp, nhà hàng sân golf, phòng thay đồ cao cấp.',
    thumbnail: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80'],
    category: 'sports',
    location: 'Long Thành, Đồng Nai',
    priceFrom: 1500000,
    priceUnit: '/người/18 lỗ',
    rating: 4.65,
    reviewCount: 670,
    amenities: ['Caddy', 'Xe điện', 'Driving range', 'Nhà hàng', 'Phòng thay đồ', 'Cho thuê gậy'],
    tags: ['Golf', 'Thể thao', 'VIP', 'Đồng Nai'],
    host: 'Long Thành Golf Management',
    hostAvatar: 'https://i.pravatar.cc/150?img=52',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-04', times: ['06:00', '07:00', '08:00', '14:00', '15:00'] },
      { date: '2025-07-05', times: ['06:30', '07:30', '13:00', '14:30'] },
    ],
  },
  {
    id: 's12',
    slug: 'wedding-venue-dalat-flower',
    title: 'Đà Lạt Flower Garden Wedding',
    subtitle: 'Địa điểm tổ chức đám cưới lý tưởng giữa vườn hoa',
    description: 'Khuôn viên 5.000m² với vườn hoa tươi thắm quanh năm. Sức chứa 300 khách. Bao gồm trang trí hoa, âm thanh ánh sáng, MC và catering cao cấp.',
    thumbnail: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80'],
    category: 'event',
    location: 'Đà Lạt, Lâm Đồng',
    priceFrom: 45000000,
    priceUnit: '/buổi',
    rating: 4.97,
    reviewCount: 85,
    amenities: ['Vườn hoa 5000m²', 'Sức chứa 300 khách', 'Catering', 'Hoa trang trí', 'Ánh sáng', 'MC', 'Phòng cô dâu'],
    tags: ['Đám cưới', 'Hoa', 'Đà Lạt', 'Lãng mạn'],
    host: 'Đà Lạt Event Studio',
    hostAvatar: 'https://i.pravatar.cc/150?img=62',
    availableSlots: [
      { date: '2025-07-12', times: ['16:00'] },
      { date: '2025-07-19', times: ['16:00'] },
    ],
  },
  {
    id: 's13',
    slug: 'boutique-hotel-hoi-an-ancient',
    title: 'Hội An Ancient House Boutique',
    subtitle: 'Khách sạn boutique trong nhà cổ 200 năm tuổi',
    description: 'Trải nghiệm sống trong ngôi nhà cổ 200 năm tuổi được cải tạo tinh tế. 8 phòng đặc biệt với nội thất gỗ cổ, sân trong với giếng cổ và vườn tược xanh mát.',
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80'],
    category: 'hotel',
    location: 'Phố cổ Hội An, Quảng Nam',
    priceFrom: 1800000,
    priceUnit: '/đêm',
    rating: 4.92,
    reviewCount: 445,
    amenities: ['Sân trong cổ', 'Bữa sáng truyền thống', 'Xe đạp miễn phí', 'Tour thành phố', 'WiFi', 'Hồ bơi nhỏ'],
    tags: ['Boutique', 'Hội An', 'Cổ trấn', 'Độc đáo'],
    host: 'Nguyễn Thị Minh Châu',
    hostAvatar: 'https://i.pravatar.cc/150?img=72',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-06', times: ['14:00'] },
      { date: '2025-07-08', times: ['14:00'] },
      { date: '2025-07-11', times: ['14:00'] },
    ],
  },
  {
    id: 's14',
    slug: 'cooking-class-hanoi',
    title: 'Hanoi Street Food Cooking Class',
    subtitle: 'Học nấu ăn đường phố Hà Nội cùng đầu bếp địa phương',
    description: 'Lớp học nấu ăn 4 tiếng: đi chợ Đồng Xuân, học nấu phở, bún chả, bánh cuốn và chè. Thầy giáo nói tiếng Anh, nhóm nhỏ tối đa 8 người.',
    thumbnail: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80'],
    category: 'tour',
    location: 'Hoàn Kiếm, Hà Nội',
    priceFrom: 650000,
    priceUnit: '/người',
    rating: 4.96,
    reviewCount: 780,
    amenities: ['Chợ tour', 'Nguyên liệu', 'Công thức', 'Bữa ăn', 'Nhóm nhỏ ≤8', 'Chứng chỉ'],
    tags: ['Nấu ăn', 'Hà Nội', 'Ẩm thực', 'Trải nghiệm'],
    host: 'Chef Phạm Việt Anh',
    hostAvatar: 'https://i.pravatar.cc/150?img=15',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-03', times: ['08:30', '14:30'] },
      { date: '2025-07-04', times: ['08:30', '14:30'] },
      { date: '2025-07-05', times: ['08:30'] },
    ],
  },
  {
    id: 's15',
    slug: 'rooftop-pool-bar-hcm',
    title: 'Sky Bar & Pool — Saigon Heights',
    subtitle: 'Bar hồ bơi tầng 32, panoramic view Sài Gòn',
    description: 'Trải nghiệm cocktail thủ công và dipping pool với 360° view Sài Gòn. DJ set cuối tuần, dress code smart casual. Đặt bàn ưu tiên trước 24h.',
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80'],
    category: 'restaurant',
    location: 'Bình Thạnh, TP. Hồ Chí Minh',
    priceFrom: 500000,
    priceUnit: '/người (minimum spend)',
    rating: 4.72,
    reviewCount: 1340,
    amenities: ['Hồ bơi', 'DJ', 'Cocktail bar', 'View 360°', 'Sunset hour', 'Dress code'],
    tags: ['Rooftop', 'Bar', 'Sài Gòn', 'Sunset'],
    host: 'Saigon Heights F&B',
    hostAvatar: 'https://i.pravatar.cc/150?img=25',
    availableSlots: [
      { date: '2025-07-04', times: ['17:00', '18:00', '19:00', '20:00'] },
      { date: '2025-07-05', times: ['16:00', '17:00', '18:00', '19:00', '20:00'] },
    ],
  },
  {
    id: 's16',
    slug: 'traditional-massage-hue',
    title: 'Ngọc Lan Spa — Massage Cung Đình Huế',
    subtitle: 'Liệu pháp massage theo bí quyết hoàng tộc triều Nguyễn',
    description: 'Spa độc quyền ứng dụng các liệu pháp massage và thảo dược theo bí quyết của các cung phi triều Nguyễn. Không gian tái hiện phòng tắm hoàng cung.',
    thumbnail: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80'],
    category: 'spa',
    location: 'TP. Huế',
    priceFrom: 680000,
    priceUnit: '/người/90 phút',
    rating: 4.91,
    reviewCount: 423,
    amenities: ['Thảo dược hoàng cung', 'Xông hơi', 'Tắm hoa', 'Trà hoàng cung', 'Phòng riêng'],
    tags: ['Spa', 'Huế', 'Hoàng cung', 'Thảo dược'],
    host: 'Ngọc Lan',
    hostAvatar: 'https://i.pravatar.cc/150?img=35',
    isInstantBook: true,
    availableSlots: [
      { date: '2025-07-03', times: ['09:00', '10:30', '14:00', '15:30', '17:00'] },
      { date: '2025-07-04', times: ['09:00', '11:00', '14:00', '16:00'] },
    ],
  },
  {
    id: 's17',
    slug: 'motorbike-tour-northwest',
    title: 'Northwest Loop Motorbike Tour 4D3N',
    subtitle: 'Chinh phục cung đường Tây Bắc Hà Giang - Lai Châu',
    description: 'Tour xe máy 4 ngày 3 đêm qua Hà Giang, đèo Mã Pì Lèng, Đồng Văn, Lai Châu. Có dẫn đường kinh nghiệm, xe semi-auto hoặc số. Phù hợp người mới và pro.',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],
    category: 'tour',
    location: 'Hà Giang',
    priceFrom: 4500000,
    priceUnit: '/người/4 ngày',
    rating: 4.89,
    reviewCount: 567,
    amenities: ['Xe máy', 'Dẫn đường', 'Homestay', 'Bữa ăn', 'Xăng', 'Bảo hiểm', 'Mũ bảo hiểm'],
    tags: ['Xe máy', 'Hà Giang', 'Tây Bắc', 'Phượt'],
    host: 'Hà Giang Loop Riders',
    hostAvatar: 'https://i.pravatar.cc/150?img=45',
    availableSlots: [
      { date: '2025-07-06', times: ['07:00'] },
      { date: '2025-07-10', times: ['07:00'] },
      { date: '2025-07-17', times: ['07:00'] },
    ],
  },
  {
    id: 's18',
    slug: 'team-building-nha-trang',
    title: 'Ocean Team Building — Nha Trang',
    subtitle: 'Hoạt động team building trên biển cho 20–200 người',
    description: 'Gói team building trọn gói: thuyền kayak, thi đấu bè nổi, lặn ngắm san hô, BBQ bãi biển. Có MC và facilitator chuyên nghiệp. Linh hoạt tùy chỉnh theo doanh nghiệp.',
    thumbnail: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80'],
    category: 'event',
    location: 'Nha Trang, Khánh Hòa',
    priceFrom: 850000,
    priceUnit: '/người (tối thiểu 20 người)',
    rating: 4.78,
    reviewCount: 234,
    amenities: ['Kayak', 'Tàu', 'BBQ', 'MC', 'Lặn ngắm san hô', 'Trang phục'],
    tags: ['Team Building', 'Biển', 'Nha Trang', 'Doanh nghiệp'],
    host: 'Ocean Events Vietnam',
    hostAvatar: 'https://i.pravatar.cc/150?img=55',
    availableSlots: [
      { date: '2025-07-19', times: ['08:00'] },
    ],
  },
  {
    id: 's13',
    slug: 'bay-khinh-khi-cau-mui-ne',
    title: 'Bay khinh khí cầu ngắm bình minh Mũi Né',
    subtitle: 'Ngắm toàn cảnh đồi cát và bờ biển từ độ cao 500m',
    description: 'Trải nghiệm ngắm bình minh ngoạn mục trên khinh khí cầu tại Phan Thiết. Chiêm ngưỡng đồi cát trắng và làn sóng xanh rì rào dưới ánh mặt trời rực rỡ.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80'],
    category: 'experience',
    location: 'Mũi Né, Bình Thuận',
    priceFrom: 3499000,
    priceUnit: '/người (tour 3 giờ)',
    rating: 4.95,
    reviewCount: 142,
    amenities: ['Đồ uống nhẹ', 'Bảo hiểm', 'Bằng chứng nhận bay', 'Xe đưa đón'],
    tags: ['Mũi Né', 'Bình minh', 'Khinh khí cầu', 'Mạo hiểm'],
    host: 'Mui Ne Ballooning',
    hostAvatar: 'https://i.pravatar.cc/150?img=12',
    isFeatured: true,
    availableSlots: [
      { date: '2026-07-05', times: ['05:00'] },
      { date: '2026-07-06', times: ['05:00'] }
    ]
  },
  {
    id: 's14',
    slug: 'tour-lan-bien-hon-mun',
    title: 'Tour lặn biển ngắm san hô Hòn Mun Nha Trang',
    subtitle: 'Khám phá thế giới đại dương cùng huấn luyện viên PADI',
    description: 'Lặn biển chuyên nghiệp khám phá hệ sinh thái san hô phong phú bậc nhất Việt Nam tại đảo Hòn Mun. Phù hợp cho cả người chưa từng lặn thử.',
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80'],
    category: 'experience',
    location: 'Đảo Hòn Mun, Nha Trang',
    priceFrom: 950000,
    priceUnit: '/người (bao gồm thiết bị)',
    rating: 4.88,
    reviewCount: 328,
    amenities: ['Thiết bị lặn', 'Huấn luyện viên', 'Bữa trưa hải sản', 'Tàu đưa đón'],
    tags: ['Nha Trang', 'Lặn biển', 'San hô', 'Đảo'],
    host: 'Nha Trang Diving Club',
    hostAvatar: 'https://i.pravatar.cc/150?img=22',
    isFeatured: true,
    availableSlots: [
      { date: '2026-07-05', times: ['08:00', '13:00'] },
      { date: '2026-07-06', times: ['08:00'] }
    ]
  },
  {
    id: 's15',
    slug: 'food-tour-ha-noi',
    title: 'Khám phá ẩm thực đường phố Hà Nội (Food Tour)',
    subtitle: 'Thưởng thức 8 món ngon trứ danh cùng Food Guide bản địa',
    description: 'Hành trình len lỏi qua các ngõ ngách Phố Cổ để thưởng thức Phở Bò truyền thống, Bún Chả, Bánh Mì và Cà Phê Trứng huyền thoại.',
    thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80'],
    category: 'experience',
    location: 'Phố Cổ, Hà Nội',
    priceFrom: 450000,
    priceUnit: '/người (3.5 giờ)',
    rating: 4.98,
    reviewCount: 512,
    amenities: ['Đồ ăn uống', 'Hướng dẫn viên', 'Bản đồ ẩm thực', 'Quà lưu niệm'],
    tags: ['Hà Nội', 'Phố Cổ', 'Ẩm thực', 'Đường phố'],
    host: 'Hanoi Food Tour Team',
    hostAvatar: 'https://i.pravatar.cc/150?img=35',
    isFeatured: true,
    availableSlots: [
      { date: '2026-07-05', times: ['11:00', '17:30'] },
      { date: '2026-07-06', times: ['17:30'] }
    ]
  },
  {
    id: 's16',
    slug: 'hoc-lam-gom-bat-trang',
    title: 'Trải nghiệm học làm gốm Bát Tràng truyền thống',
    subtitle: 'Tự tay nhào nặn và vẽ sản phẩm gốm của riêng bạn',
    description: 'Lớp học làm gốm thủ công dưới sự hướng dẫn của nghệ nhân làng gốm Bát Tràng. Sản phẩm của bạn sẽ được nung chín và gửi về tận nhà.',
    thumbnail: 'https://images.unsplash.com/photo-1565192647048-f997ded87958?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1565192647048-f997ded87958?w=800&q=80'],
    category: 'experience',
    location: 'Làng gốm Bát Tràng, Hà Nội',
    priceFrom: 250000,
    priceUnit: '/người (bao gồm đất sét)',
    rating: 4.82,
    reviewCount: 194,
    amenities: ['Đất sét & màu vẽ', 'Sản phẩm hoàn thiện', 'Nước uống', 'Nghệ nhân'],
    tags: ['Bát Tràng', 'Học làm gốm', 'Thủ công', 'Văn hóa'],
    host: 'Bát Tràng Pottery Lab',
    hostAvatar: 'https://i.pravatar.cc/150?img=42',
    isFeatured: false,
    availableSlots: [
      { date: '2026-07-05', times: ['09:00', '14:00'] },
      { date: '2026-07-06', times: ['09:00', '14:00'] }
    ]
  }
];

export const FEATURED_SERVICES = SERVICES.filter(s => s.isFeatured);

// ── Blog Posts ──────────────────────────────────────────────────────
export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  thumbnail: string;
  category: string;
  author: string;
  authorAvatar: string;
  readTime: number;
  publishedAt: string;
  tags: string[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    slug: 'kinh-nghiem-du-lich-da-lat',
    title: '10 điều cần biết khi du lịch Đà Lạt lần đầu',
    excerpt: 'Từ thời điểm tốt nhất để đến, các món ăn nhất định phải thử đến những địa điểm check-in ít người biết — hướng dẫn đầy đủ cho chuyến đi Đà Lạt hoàn hảo.',
    thumbnail: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80',
    category: 'Cẩm nang du lịch',
    author: 'Trần Minh Hiếu',
    authorAvatar: 'https://i.pravatar.cc/150?img=11',
    readTime: 8,
    publishedAt: '2025-06-28',
    tags: ['Đà Lạt', 'Du lịch', 'Kinh nghiệm'],
  },
  {
    id: 'b2',
    slug: 'spa-wellness-trend-2025',
    title: 'Xu hướng Spa & Wellness 2025: Thiên nhiên và Mindfulness',
    excerpt: 'Năm 2025 chứng kiến sự bùng nổ của các liệu pháp wellness kết hợp thiên nhiên. Từ forest bathing đến sound healing — những trải nghiệm này đang thay đổi ngành spa.',
    thumbnail: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&q=80',
    category: 'Wellness',
    author: 'Nguyễn Thùy Linh',
    authorAvatar: 'https://i.pravatar.cc/150?img=21',
    readTime: 6,
    publishedAt: '2025-06-25',
    tags: ['Spa', 'Wellness', 'Xu hướng'],
  },
  {
    id: 'b3',
    slug: 'am-thuc-duong-pho-hoi-an',
    title: 'Tour ẩm thực đường phố Hội An: Ăn gì, ở đâu?',
    excerpt: 'Cao Lầu, Mì Quảng, Bánh Mì Phượng, Bánh Bao Vạc — bản đồ ẩm thực Hội An cho người mê đồ ăn. Kèm địa chỉ cụ thể và giờ mở cửa.',
    thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    category: 'Ẩm thực',
    author: 'Lê Bảo Châu',
    authorAvatar: 'https://i.pravatar.cc/150?img=31',
    readTime: 10,
    publishedAt: '2025-06-20',
    tags: ['Hội An', 'Ẩm thực', 'Đường phố'],
  },
  {
    id: 'b4',
    slug: 'cach-dat-phong-khach-san-gia-tot',
    title: '5 bí quyết đặt phòng khách sạn giá tốt nhất',
    excerpt: 'Thời điểm đặt phòng, cách so sánh giá, sử dụng điểm loyalty và những mẹo ít người biết để luôn có mức giá tốt nhất khi đặt phòng khách sạn.',
    thumbnail: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    category: 'Mẹo hay',
    author: 'Phạm Quốc Anh',
    authorAvatar: 'https://i.pravatar.cc/150?img=41',
    readTime: 5,
    publishedAt: '2025-06-18',
    tags: ['Khách sạn', 'Tiết kiệm', 'Mẹo hay'],
  },
  {
    id: 'b5',
    slug: 'ha-long-cruise-review',
    title: 'Review thực tế: 2 ngày trên du thuyền Hạ Long',
    excerpt: 'Trải nghiệm thực tế sau chuyến đi 2 ngày 1 đêm trên du thuyền luxury Hạ Long. Giá trị so với tiền bỏ ra? Có nên đặt qua app hay trực tiếp?',
    thumbnail: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80',
    category: 'Review',
    author: 'Võ Thanh Tùng',
    authorAvatar: 'https://i.pravatar.cc/150?img=51',
    readTime: 12,
    publishedAt: '2025-06-15',
    tags: ['Hạ Long', 'Cruise', 'Review'],
  },
  {
    id: 'b6',
    slug: 'to-chuc-dam-cuoi-da-lat',
    title: 'Tổ chức đám cưới tại Đà Lạt: Chi phí & Timeline',
    excerpt: 'Chi tiết chi phí thực tế khi tổ chức đám cưới tại Đà Lạt từ 100–300 khách: venue, hoa, catering, nhiếp ảnh, trang điểm. Kèm timeline lên kế hoạch 12 tháng.',
    thumbnail: 'https://images.unsplash.com/photo-1550005809-91ad75fb315f?w=800&q=80',
    category: 'Sự kiện',
    author: 'Trần Thị Hồng Nhung',
    authorAvatar: 'https://i.pravatar.cc/150?img=61',
    readTime: 15,
    publishedAt: '2025-06-10',
    tags: ['Đám cưới', 'Đà Lạt', 'Sự kiện', 'Venue'],
  },
];
