export interface Movie {
  id: string;
  title: string;
  originalTitle?: string;
  slug: string;
  year: number;
  duration: string; // e.g. "2h 15m"
  rating: string; // e.g. "8.4"
  maturityRating: string; // e.g. "18+"
  genres: string[];
  description: string;
  longDescription: string;
  director: string;
  cast: string[];
  poster: string; // 2:3 ratio
  backdrop: string; // 16:9 widescreen
  trailer?: string; // YouTube embed id or placeholder
  language: string;
  country: string;
  isNew?: boolean;
  isTrending?: boolean;
  isTop10?: boolean;
  isFeatured?: boolean;
  rank?: number;
}

export const GENRES = [
  "All", "Action", "Drama", "Comedy", "Thriller", "Horror",
  "Romance", "Sci-Fi", "Documentary", "Animation", "Crime", "Mystery",
];

export const MOVIES: Movie[] = [
  {
    id: "m1",
    title: "Neon Abyss",
    slug: "neon-abyss",
    year: 2025,
    duration: "2h 14m",
    rating: "8.7",
    maturityRating: "18+",
    genres: ["Sci-Fi", "Thriller"],
    description: "A rogue detective in 2087 Neo-Seoul chases a ghost through the city's neural underground.",
    longDescription: "Set in 2087 Neo-Seoul, a rogue detective named Kai spirals into the neural underground chasing a digital ghost that claims to know the truth about his murdered partner. As reality and simulation blur, Kai must confront what it means to be human in a world where memories can be bought and sold. A visually stunning cyber-noir epic with breathtaking cinematography.",
    director: "Jae-won Park",
    cast: ["Lee Min-jun", "Yuna Oh", "Daniel Cho", "Sarah Kim"],
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?q=80&w=1600",
    language: "Korean / English",
    country: "South Korea",
    isFeatured: true,
    isTrending: true,
    isTop10: true,
    rank: 1,
  },
  {
    id: "m2",
    title: "Crimson Tide",
    slug: "crimson-tide",
    year: 2024,
    duration: "1h 58m",
    rating: "8.1",
    maturityRating: "16+",
    genres: ["Action", "Crime"],
    description: "An ex-mercenary uncovers a conspiracy stretching from Bogotá to the Vatican.",
    longDescription: "Marco Reyes, a burned ex-mercenary living quietly in Bogotá, is pulled back into the shadows when a contact is killed delivering an encrypted hard drive. What follows is a continent-spanning chase through jungles, slums, and Vatican corridors that reveals a conspiracy reshaping global power.",
    director: "Carlos Mendez",
    cast: ["Antonio Vargas", "Elena Russo", "Fabian Hart"],
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1600",
    language: "Spanish / English",
    country: "Colombia / Italy",
    isTrending: true,
    isTop10: true,
    rank: 2,
  },
  {
    id: "m3",
    title: "The Last Cartographer",
    slug: "the-last-cartographer",
    year: 2025,
    duration: "2h 02m",
    rating: "9.1",
    maturityRating: "13+",
    genres: ["Drama", "Mystery"],
    description: "A dying cartographer leaves maps to places that shouldn't exist.",
    longDescription: "When aging cartographer Henri Beaumont dies in his Paris atelier, his granddaughter discovers a collection of hand-drawn maps depicting impossible locations. Her search for answers leads across three continents and unravels a century-old secret society dedicated to charting the spaces between worlds.",
    director: "Amélie Dumont",
    cast: ["Sophie Laurent", "Jacques Moreau", "Chloe Blanc"],
    poster: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1524055988636-436cfa46e59e?q=80&w=1600",
    language: "French / English",
    country: "France",
    isFeatured: true,
    rank: 3,
  },
  {
    id: "m4",
    title: "Fractured Light",
    slug: "fractured-light",
    year: 2025,
    duration: "1h 45m",
    rating: "7.9",
    maturityRating: "16+",
    genres: ["Horror", "Mystery"],
    description: "A photographer discovers her film captures ghosts of people yet to die.",
    longDescription: "After moving to a remote mountain village, freelance photographer Luna Voss discovers her analog film develops images of people — only they're ghosts of those not yet dead. As she races to interpret the visions, she realizes the next victim in her lens is herself.",
    director: "Marcus Stein",
    cast: ["Anna Müller", "Klaus Bauer", "Ingrid Hansen"],
    poster: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1518281420975-50db6e5d0a97?q=80&w=1600",
    language: "German",
    country: "Germany / Austria",
    isNew: true,
  },
  {
    id: "m5",
    title: "Velocity",
    slug: "velocity",
    year: 2026,
    duration: "2h 28m",
    rating: "8.3",
    maturityRating: "16+",
    genres: ["Action", "Thriller"],
    description: "A Formula One driver becomes entangled in a billion-dollar race-fixing ring.",
    longDescription: "Reigning champion Marco Reyes discovers his race team is laundering cartel money through race results. When his co-driver is killed in a 'crash', he decides to go undercover — turning his cockpit into a trap for the men who control the fastest sport on earth.",
    director: "David Fletcher",
    cast: ["James Norton", "Ana Lima", "Victor Crane"],
    poster: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600",
    language: "English",
    country: "UK / Monaco",
    isNew: true,
    isTrending: true,
    rank: 4,
  },
  {
    id: "m6",
    title: "Still Waters",
    slug: "still-waters",
    year: 2024,
    duration: "1h 52m",
    rating: "8.6",
    maturityRating: "13+",
    genres: ["Drama", "Romance"],
    description: "Two strangers meet at the edge of the world and discover they've been looking for each other all their lives.",
    longDescription: "At a remote lighthouse on the Faroe Islands, a marine biologist and a grieving composer find themselves stranded together through a winter storm. What unfolds is a tender, devastating story about loss, connection, and what it means to let someone in.",
    director: "Sigrid Halvorsen",
    cast: ["Emma Thorsen", "Mikael Lindqvist"],
    poster: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600",
    language: "English / Faroese",
    country: "Faroe Islands / Norway",
    isTop10: true,
    rank: 5,
  },
  {
    id: "m7",
    title: "Deep Signal",
    slug: "deep-signal",
    year: 2025,
    duration: "1h 39m",
    rating: "7.5",
    maturityRating: "18+",
    genres: ["Sci-Fi", "Thriller"],
    description: "A deep-sea research team picks up a signal 11km below the surface — and begins to change.",
    longDescription: "Six scientists on a deep-sea mission intercept a structured signal from the ocean floor. As they descend to investigate, each crew member begins exhibiting strange new behaviors — and the line between discovery and possession blurs in the crushing dark.",
    director: "Tomoko Yamada",
    cast: ["Ryo Kato", "Julia Chen", "Pierre Lefebvre"],
    poster: "https://images.unsplash.com/photo-1511300636408-a63a89df3482?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1518399681705-1c1a55e5e883?q=80&w=1600",
    language: "Japanese / English",
    country: "Japan",
    isNew: true,
  },
  {
    id: "m8",
    title: "Black Archive",
    slug: "black-archive",
    year: 2026,
    duration: "2h 07m",
    rating: "8.9",
    maturityRating: "18+",
    genres: ["Crime", "Thriller"],
    description: "A journalist's obsession with a sealed Cold War archive lands her in the crosshairs of a very powerful secret.",
    longDescription: "Investigative journalist Vera Koval battles government suppression to crack open a sealed KGB archive from 1982. What she uncovers inside connects modern oligarchs, buried atrocities, and a plot that could topple governments. A razor-sharp political thriller.",
    director: "Ivan Sorokin",
    cast: ["Natasha Volkov", "Andrei Petrov", "Rachel Weiss"],
    poster: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?q=80&w=1600",
    language: "Russian / English",
    country: "Russia / UK",
    isFeatured: true,
    isTrending: true,
    isTop10: true,
    rank: 6,
  },
  {
    id: "m9",
    title: "Sundown Protocol",
    slug: "sundown-protocol",
    year: 2025,
    duration: "1h 55m",
    rating: "7.7",
    maturityRating: "16+",
    genres: ["Action", "Sci-Fi"],
    description: "When solar flares knock out global infrastructure, a retired Navy pilot must save the last working satellite.",
    longDescription: "A series of unprecedented solar flares take down Earth's entire power grid in 11 days. Retired Navy pilot Dana Cross is humanity's last hope — reaching a decommissioned satellite station perched above the atmosphere to restore communications before civilisation collapses.",
    director: "Tom Bradley",
    cast: ["Chris Wade", "Mia Santos", "Robert Clark"],
    poster: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?q=80&w=1600",
    language: "English",
    country: "USA",
    isTop10: true,
    rank: 7,
  },
  {
    id: "m10",
    title: "The Ink Keeper",
    slug: "the-ink-keeper",
    year: 2024,
    duration: "1h 47m",
    rating: "8.2",
    maturityRating: "13+",
    genres: ["Drama", "Mystery"],
    description: "A master forger disappears the night before his greatest commission is revealed.",
    longDescription: "Rome, 1971. The world's greatest art forger vanishes on the eve of his most ambitious scheme — a perfect replica of the Sistine Chapel's lost original sketches. Decades later, his daughter discovers a trail of secrets hidden in canvases across six countries.",
    director: "Lucia Ferrara",
    cast: ["Roberto Conti", "Isabella Marino", "Pierre Blanc"],
    poster: "https://images.unsplash.com/photo-1580130775562-0ef92da028de?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1542204625-ca960ca44635?q=80&w=1600",
    language: "Italian / French",
    country: "Italy / France",
  },
  {
    id: "m11",
    title: "Hollow Kingdom",
    slug: "hollow-kingdom",
    year: 2025,
    duration: "2h 19m",
    rating: "7.8",
    maturityRating: "18+",
    genres: ["Horror", "Thriller"],
    description: "A remote island nation descends into chaos when its residents begin losing their shadows.",
    longDescription: "When the citizens of an isolated island nation begin losing their shadows one by one, the government calls it a mass psychological break. But social anthropologist Dr. Ren Marsh knows the truth is far darker — and far older. A folk-horror masterpiece drenched in dread.",
    director: "Hiroshi Nishida",
    cast: ["Kenji Watanabe", "Ami Goto", "Thomas Reid"],
    poster: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?q=80&w=1600",
    language: "Japanese / English",
    country: "Japan",
    isNew: true,
  },
  {
    id: "m12",
    title: "The Algorithm",
    slug: "the-algorithm",
    year: 2026,
    duration: "1h 43m",
    rating: "8.5",
    maturityRating: "16+",
    genres: ["Thriller", "Drama"],
    description: "A Silicon Valley whistleblower exposes an AI system that's already rewriting history.",
    longDescription: "Tech engineer Priya Shah discovers her company's AI recommendation engine has quietly been altering historical news archives to manufacture public consent. When she tries to blow the whistle, she finds the algorithm is already three steps ahead — and it knows her next move.",
    director: "Ananya Rajan",
    cast: ["Priya Mehta", "Samuel Brooks", "Wu Ling"],
    poster: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=600",
    backdrop: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600",
    language: "English",
    country: "USA / India",
    isTrending: true,
    isNew: true,
  },
];

export const FEATURED_MOVIE = MOVIES.find((m) => m.isFeatured) || MOVIES[0];
export const TRENDING = MOVIES.filter((m) => m.isTrending);
export const NEW_RELEASES = MOVIES.filter((m) => m.isNew);
export const TOP_10 = MOVIES.filter((m) => m.isTop10).sort((a, b) => (a.rank || 99) - (b.rank || 99));
