// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
// VLOG PLATFORM â€” Mock Data
// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

export interface VlogPost {
  id: string;
  slug: string;
  title: string;
  description: string;
  thumbnail: string;
  videoUrl: string;
  duration: string;
  creator: Creator;
  category: string;
  tags: string[];
  views: number;
  likes: number;
  comments: number;
  publishedAt: string;
  isFeatured?: boolean;
  isTrending?: boolean;
}

export interface Creator {
  id: string;
  handle: string;
  name: string;
  avatar: string;
  banner: string;
  bio: string;
  subscribers: number;
  totalViews: number;
  category: string;
  isVerified?: boolean;
  socialLinks: { platform: string; url: string }[];
}

export const VLOG_CATEGORIES = [
  { id: 'all', label: 'Táº¥t cáº£' },
  { id: 'travel', label: 'Du lá»‹ch ðŸŒ' },
  { id: 'food', label: 'áº¨m thá»±c ðŸœ' },
  { id: 'lifestyle', label: 'Lifestyle âœ¨' },
  { id: 'tech', label: 'CÃ´ng nghá»‡ ðŸ’»' },
  { id: 'beauty', label: 'LÃ m Ä‘áº¹p ðŸ’„' },
  { id: 'finance', label: 'TÃ i chÃ­nh ðŸ’°' },
  { id: 'fitness', label: 'Sá»©c khá»e ðŸ’ª' },
];

export const CREATORS: Creator[] = [
  {
    id: 'cr1',
    handle: 'hoanganh_travel',
    name: 'HoÃ ng Anh Travel',
    avatar: 'https://i.pravatar.cc/150?img=20',
    banner: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80',
    bio: 'KhÃ¡m phÃ¡ 50 quá»‘c gia trong 3 nÄƒm. ChuyÃªn vlog du lá»‹ch budget vÃ  luxury. Má»—i tuáº§n 1 video má»›i.',
    subscribers: 842000,
    totalViews: 45000000,
    category: 'travel',
    isVerified: true,
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'tiktok', url: '#' },
    ],
  },
  {
    id: 'cr2',
    handle: 'bep_viet_cuoi_ngay',
    name: 'Báº¿p Viá»‡t Cuá»‘i NgÃ y',
    avatar: 'https://i.pravatar.cc/150?img=35',
    banner: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
    bio: 'áº¨m thá»±c Viá»‡t tá»« ba miá»n. CÃ´ng thá»©c chuáº©n vá»‹, dá»… lÃ m táº¡i nhÃ . 500+ video náº¥u Äƒn.',
    subscribers: 1200000,
    totalViews: 120000000,
    category: 'food',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }],
  },
  {
    id: 'cr3',
    handle: 'techviet_review',
    name: 'TechViet Review',
    avatar: 'https://i.pravatar.cc/150?img=50',
    banner: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80',
    bio: 'Review tech tháº­t thÃ . KhÃ´ng sponsor che giáº¥u, khÃ´ng PR quÃ¡ má»©c. Chá»‰ sá»± tháº­t.',
    subscribers: 560000,
    totalViews: 28000000,
    category: 'tech',
    isVerified: true,
    socialLinks: [{ platform: 'twitter', url: '#' }],
  },

  {
    id: 'cr4',
    handle: 'beauty_linhly',
    name: 'Linh Ly Beauty',
    avatar: 'https://i.pravatar.cc/150?img=47',
    banner: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200&q=80',
    bio: 'Chuyên gia makeup & skincare. 8 nam kinh nghi?m. Review honest, tutorial d? hi?u.',
    subscribers: 2100000,
    totalViews: 200000000,
    category: 'beauty',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }, { platform: 'tiktok', url: '#' }],
  },
  {
    id: 'cr5',
    handle: 'tai_chinh_thong_minh',
    name: 'Tài Chính Thông Minh',
    avatar: 'https://i.pravatar.cc/150?img=12',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
    bio: 'CFA charterholder. Ð?u tu ch?ng khoán, crypto, b?t d?ng s?n. Giúp ngu?i Vi?t làm giàu thông minh.',
    subscribers: 3500000,
    totalViews: 450000000,
    category: 'finance',
    isVerified: true,
    socialLinks: [{ platform: 'youtube', url: '#' }],
  },
  {
    id: 'cr6',
    handle: 'coach_duc_fitness',
    name: 'Coach Ð?c Fitness',
    avatar: 'https://i.pravatar.cc/150?img=8',
    banner: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
    bio: 'HLV th? hình cá nhân 10 nam. Chuyên gi?m cân, tang co. Mi?n phí hoàn toàn!',
    subscribers: 890000,
    totalViews: 78000000,
    category: 'fitness',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }],
  }];
export const VLOG_POSTS: VlogPost[] = [
  {
    id: 'v1',
    slug: 'japan-sakura-2025',
    title: '7 ngÃ y á»Ÿ Nháº­t mÃ¹a hoa anh Ä‘Ã o 2025 â€” Chi phÃ­ tháº­t & Nhá»¯ng tráº£i nghiá»‡m khÃ´ng thá»ƒ quÃªn',
    description: 'Budget 20 triá»‡u cho 7 ngÃ y Nháº­t Báº£n: Tokyo, Kyoto, Osaka. Xem hoa anh Ä‘Ã o, Äƒn sushi tháº­t sá»±, ngá»§ capsule hotel. KHÃ”NG Cáº®T XÃ‰N!',
    thumbnail: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '24:35',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Nháº­t Báº£n', 'Du lá»‹ch', 'Hoa anh Ä‘Ã o', 'Budget travel'],
    views: 2840000,
    likes: 142000,
    comments: 8940,
    publishedAt: '2025-04-10T08:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v2',
    slug: 'pho-ha-noi-authentic',
    title: 'BÃ­ quyáº¿t náº¥u Phá»Ÿ HÃ  Ná»™i Ä‘Ãºng vá»‹ â€” NÆ°á»›c dÃ¹ng trong veo, thÆ¡m ngÃ o ngáº¡t',
    description: 'CÃ´ng thá»©c phá»Ÿ HÃ  Ná»™i gia truyá»n 3 Ä‘á»i. Tá»« cÃ¡ch chá»n xÆ°Æ¡ng, hoa há»“i Ä‘áº¿n nÆ°á»›c máº¯m thÃªm vÃ o lÃºc nÃ o. Video dÃ i 30 phÃºt nhÆ°ng xá»©ng Ä‘Ã¡ng tá»«ng giÃ¢y.',
    thumbnail: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '31:22',
    creator: CREATORS[1],
    category: 'food',
    tags: ['Phá»Ÿ', 'Náº¥u Äƒn', 'HÃ  Ná»™i', 'áº¨m thá»±c Viá»‡t'],
    views: 5600000,
    likes: 280000,
    comments: 22400,
    publishedAt: '2025-06-15T10:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v3',
    slug: 'iphone-16-pro-review-viet',
    title: 'iPhone 16 Pro Max Review sau 3 thÃ¡ng dÃ¹ng tháº­t â€” ÄÃ¡ng tiá»n khÃ´ng?',
    description: 'KhÃ´ng pháº£i review 1 tuáº§n. TÃ´i dÃ¹ng iPhone 16 Pro Max 3 thÃ¡ng: camera, pin, chip A18 Pro, nhiá»‡t Ä‘á»™. Káº¿t quáº£ gÃ¢y báº¥t ngá»!',
    thumbnail: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '18:45',
    creator: CREATORS[2],
    category: 'tech',
    tags: ['iPhone', 'Apple', 'Review', 'Smartphone'],
    views: 1240000,
    likes: 62000,
    comments: 4800,
    publishedAt: '2025-06-20T09:00:00Z',
    isTrending: true,
  },
  {
    id: 'v4',
    slug: 'danang-hidden-gems',
    title: 'ÄÃ  Náºµng KHÃ”NG dÃ nh cho khÃ¡ch du lá»‹ch â€” 10 Ä‘á»‹a Ä‘iá»ƒm ngÆ°á»i local má»›i biáº¿t',
    description: 'Bá» qua Cáº§u Rá»“ng vÃ  BÃ  NÃ  Hills, tÃ´i sáº½ show báº¡n ÄÃ  Náºµng mÃ  chá»‰ ngÆ°á»i sá»‘ng á»Ÿ Ä‘Ã¢y má»›i biáº¿t.',
    thumbnail: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '20:10',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['ÄÃ  Náºµng', 'Du lá»‹ch ná»™i Ä‘á»‹a', 'Hidden gems'],
    views: 890000,
    likes: 44500,
    comments: 3200,
    publishedAt: '2025-06-25T07:00:00Z',
  },
  {
    id: 'v5',
    slug: 'banh-mi-saigon-secrets',
    title: 'HÃ nh trÃ¬nh tÃ¬m BÃ¡nh MÃ¬ ngon nháº¥t SÃ i GÃ²n â€” Review 20 tiá»‡m trong 2 ngÃ y',
    description: 'TÃ´i Ä‘Ã£ Äƒn 20 á»• bÃ¡nh mÃ¬ trong 2 ngÃ y Ä‘á»ƒ tÃ¬m ra Ä‘Ã¢u lÃ  bÃ¡nh mÃ¬ ngon nháº¥t SÃ i GÃ²n. Bao tá»­ vÃ  Ä‘am mÃª tháº­t sá»±!',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '27:18',
    creator: CREATORS[1],
    category: 'food',
    tags: ['BÃ¡nh mÃ¬', 'SÃ i GÃ²n', 'Street food', 'Review Äƒn'],
    views: 3200000,
    likes: 160000,
    comments: 12800,
    publishedAt: '2025-06-28T11:00:00Z',
    isTrending: true,
  },
  {
    id: 'v6',
    slug: 'macbook-m4-vs-windows',
    title: 'MacBook M4 Pro vs Windows Gaming Laptop â€” CÃ¡i nÃ o Ä‘Ã¡ng mua cho dÃ¢n lÃ m viá»‡c VN?',
    description: 'So sÃ¡nh thá»±c chiáº¿n cho ngÆ°á»i Viá»‡t. MacBook M4 Pro 60 triá»‡u vs Gaming Laptop 35 triá»‡u. Benchmark, pin, mÃ n hÃ¬nh, phÃ¹ há»£p cÃ´ng viá»‡c nÃ o?',
    thumbnail: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '22:55',
    creator: CREATORS[2],
    category: 'tech',
    tags: ['MacBook', 'Laptop', 'So sÃ¡nh', 'Mua hÃ ng'],
    views: 780000,
    likes: 39000,
    comments: 5600,
    publishedAt: '2025-06-30T08:00:00Z',
  },

  {
    id: 'v7',
    slug: 'skincare-routine-viet-6-buoc',
    title: 'Skincare Routine 6 bu?c cho da Vi?t — Da h?t m?n sau 30 ngày (K?t qu? th?t)',
    description: 'Routine du?ng da phù h?p khí h?u Vi?t Nam nóng ?m. S?n ph?m bình dân d?n cao c?p.',
    thumbnail: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '19:42',
    creator: CREATORS[3],
    category: 'beauty',
    tags: ['Skincare', 'Làm d?p', 'Da m?n', 'Review'],
    views: 2100000,
    likes: 105000,
    comments: 9200,
    publishedAt: '2025-07-01T08:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v8',
    slug: 'dau-tu-chung-khoan-tuoi-25',
    title: 'Tôi d?u tu ch?ng khoán t? nam 25 tu?i — 5 nam sau k?t qu? b?t ng?',
    description: 'Hành trình d?u tu ch?ng khoán th?c t?: t? tay tr?ng d?n danh m?c 500 tri?u.',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '33:12',
    creator: CREATORS[4],
    category: 'finance',
    tags: ['Ð?u tu', 'Ch?ng khoán', 'Tài chính cá nhân', 'FIRE'],
    views: 4500000,
    likes: 225000,
    comments: 18600,
    publishedAt: '2025-07-02T07:00:00Z',
    isTrending: true,
  },
  {
    id: 'v9',
    slug: 'gym-nguoi-moi-bat-dau',
    title: 'Gym cho ngu?i m?i b?t d?u — L?ch t?p 5 ngày/tu?n, tang co gi?m m? cùng lúc',
    description: 'Chuong trình t?p gym full body cho beginner. Không c?n PT, không c?n t?n ti?n supplement.',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '28:06',
    creator: CREATORS[5],
    category: 'fitness',
    tags: ['Gym', 'T?p luy?n', 'Tang co', 'S?c kh?e'],
    views: 1800000,
    likes: 90000,
    comments: 7400,
    publishedAt: '2025-07-03T09:00:00Z',
  },
  {
    id: 'v10',
    slug: 'sapa-4-mua-trong-1-ngay',
    title: 'Sa Pa 4 mùa trong 1 ngày — Tr?i nghi?m không tu?ng t?i d?nh Fansipan',
    description: 'Khi mây mù, n?ng vàng, mua và suong l?nh d?n trong cùng m?t ngày leo Fansipan.',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '16:30',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Sa Pa', 'Fansipan', 'Du l?ch mi?n núi', 'C?nh d?p Vi?t Nam'],
    views: 1560000,
    likes: 78000,
    comments: 5100,
    publishedAt: '2025-07-04T06:00:00Z',
  },
  {
    id: 'v11',
    slug: 'make-up-co-gau-style',
    title: 'Make-up Cô Gâu Style dang HOT — T? làm ? nhà ch? 10 phút',
    description: 'Trend make-up cô gâu dang viral. Tôi hu?ng d?n step by step t? base d?n blush.',
    thumbnail: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '14:22',
    creator: CREATORS[3],
    category: 'beauty',
    tags: ['Make-up', 'Trend', 'Tutorial'],
    views: 3400000,
    likes: 170000,
    comments: 14500,
    publishedAt: '2025-07-05T10:00:00Z',
    isTrending: true,
  },
  {
    id: 'v12',
    slug: 'bitcoin-crypto-viet-nam-2025',
    title: 'Bitcoin & Crypto ? Vi?t Nam 2025 — H?p pháp chua? Mua th? nào?',
    description: 'Toàn b? nh?ng gì b?n c?n bi?t v? d?u tu crypto t?i Vi?t Nam.',
    thumbnail: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '41:08',
    creator: CREATORS[4],
    category: 'finance',
    tags: ['Bitcoin', 'Crypto', 'Ð?u tu'],
    views: 6200000,
    likes: 310000,
    comments: 28000,
    publishedAt: '2025-07-06T07:00:00Z',
    isTrending: true,
  },
  {
    id: 'v13',
    slug: 'chay-bo-marathon-tu-zero',
    title: 'T? Zero d?n hoàn thành Marathon 42km trong 6 tháng',
    description: 'Không ph?i v?n d?ng viên chuyên nghi?p, tôi hoàn thành marathon d?u tiên t? con s? 0.',
    thumbnail: 'https://images.unsplash.com/photo-1461897104016-0b3b00cc81ee?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '35:50',
    creator: CREATORS[5],
    category: 'fitness',
    tags: ['Marathon', 'Ch?y b?', 'Luy?n t?p'],
    views: 920000,
    likes: 46000,
    comments: 3800,
    publishedAt: '2025-07-07T06:30:00Z',
  },
  {
    id: 'v14',
    slug: 'mui-ne-phan-thiet-5-trieu',
    title: 'Du l?ch Mui Né - Phan Thi?t 5 tri?u/ngu?i — An ngon, ? d?p, chill h?t m?c',
    description: '3 ngày 2 dêm v?i 5 tri?u. Bãi bi?n, làng chài, d?i cát h?ng và h?i s?n tuoi r?.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '23:15',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Mui Né', 'Phan Thi?t', 'Bi?n', 'Budget travel'],
    views: 2100000,
    likes: 105000,
    comments: 8900,
    publishedAt: '2025-07-08T08:00:00Z',
  }];
export const TRENDING_POSTS = VLOG_POSTS.filter(p => p.isTrending);
export const FEATURED_POST = VLOG_POSTS.find(p => p.isFeatured) || VLOG_POSTS[0];


export const PLAYLISTS = [
  {
    id: 'pl1',
    title: 'Du l?ch Ðông Nam Á',
    description: 'Khám phá 10 qu?c gia v?i budget 15 tri?u',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    creator: CREATORS[0],
    videoCount: 8,
    totalViews: 12000000,
  },
  {
    id: 'pl2',
    title: 'N?u an Vi?t Nam tr?n v?n',
    description: '50+ công th?c ?m th?c 3 mi?n',
    thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    creator: CREATORS[1],
    videoCount: 52,
    totalViews: 45000000,
  },
  {
    id: 'pl3',
    title: 'Tech Review 2025',
    description: 'T?t c? thi?t b? công ngh? hot nh?t nam',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
    creator: CREATORS[2],
    videoCount: 24,
    totalViews: 8500000,
  },
  {
    id: 'pl4',
    title: 'Làm giàu t? d?u tu',
    description: 'T? ch?ng khoán d?n b?t d?ng s?n',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    creator: CREATORS[4],
    videoCount: 18,
    totalViews: 22000000,
  },
];
