// ══════════════════════════════════════════
// VLOG PLATFORM — Mock Data
// ══════════════════════════════════════════

export interface VlogPost {
  id: string;
  slug: string;
  title: string;
  description: string;
  thumbnail: string;
  videoUrl: string;
  duration: string;
  creator: Creator;
  category: string;
  tags: string[];
  views: number;
  likes: number;
  comments: number;
  publishedAt: string;
  isFeatured?: boolean;
  isTrending?: boolean;
}

export interface Creator {
  id: string;
  handle: string;
  name: string;
  avatar: string;
  banner: string;
  bio: string;
  subscribers: number;
  totalViews: number;
  category: string;
  isVerified?: boolean;
  socialLinks: { platform: string; url: string }[];
}

export const VLOG_CATEGORIES = [
  { id: 'all', label: 'Tất cả' },
  { id: 'travel', label: 'Du lịch 🗺️' },
  { id: 'food', label: 'Ẩm thực 🍳' },
  { id: 'lifestyle', label: 'Lifestyle ✨' },
  { id: 'tech', label: 'Công nghệ 💻' },
  { id: 'beauty', label: 'Làm đẹp 💄' },
  { id: 'finance', label: 'Tài chính 💰' },
  { id: 'fitness', label: 'Sức khỏe 💪' },
];

export const CREATORS: Creator[] = [
  {
    id: 'cr1',
    handle: 'hoanganh_travel',
    name: 'Hoàng Anh Travel',
    avatar: 'https://i.pravatar.cc/150?img=20',
    banner: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80',
    bio: 'Khám phá 50 quốc gia trong 3 năm. Chuyên vlog du lịch tự túc và sang chảnh. Mỗi tuần 1 video mới.',
    subscribers: 842000,
    totalViews: 45000000,
    category: 'travel',
    isVerified: true,
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'tiktok', url: '#' },
    ],
  },
  {
    id: 'cr2',
    handle: 'bep_viet_cuoi_ngay',
    name: 'Bếp Việt Cuối Ngày',
    avatar: 'https://i.pravatar.cc/150?img=35',
    banner: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
    bio: 'Ẩm thực Việt từ ba miền. Công thức chuẩn vị, dễ làm tại nhà. 500+ video nấu ăn.',
    subscribers: 1200000,
    totalViews: 120000000,
    category: 'food',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }],
  },
  {
    id: 'cr3',
    handle: 'techviet_review',
    name: 'TechViet Review',
    avatar: 'https://i.pravatar.cc/150?img=50',
    banner: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80',
    bio: 'Review công nghệ chân thực. Không quảng cáo che giấu, không PR quá mức. Chỉ nói sự thật.',
    subscribers: 560000,
    totalViews: 28000000,
    category: 'tech',
    isVerified: true,
    socialLinks: [{ platform: 'twitter', url: '#' }],
  },
  {
    id: 'cr4',
    handle: 'beauty_linhly',
    name: 'Linh Ly Beauty',
    avatar: 'https://i.pravatar.cc/150?img=47',
    banner: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200&q=80',
    bio: 'Chuyên gia trang điểm & chăm sóc da. 8 năm kinh nghiệm. Đánh giá chân thật, hướng dẫn dễ hiểu.',
    subscribers: 2100000,
    totalViews: 200000000,
    category: 'beauty',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }, { platform: 'tiktok', url: '#' }],
  },
  {
    id: 'cr5',
    handle: 'tai_chinh_thong_minh',
    name: 'Tài Chính Thông Minh',
    avatar: 'https://i.pravatar.cc/150?img=12',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
    bio: 'CFA charterholder. Đầu tư chứng khoán, crypto, bất động sản. Giúp người Việt tích lũy tài sản thông minh.',
    subscribers: 3500000,
    totalViews: 450000000,
    category: 'finance',
    isVerified: true,
    socialLinks: [{ platform: 'youtube', url: '#' }],
  },
  {
    id: 'cr6',
    handle: 'coach_duc_fitness',
    name: 'Coach Đức Fitness',
    avatar: 'https://i.pravatar.cc/150?img=8',
    banner: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
    bio: 'HLV thể hình cá nhân 10 năm. Chuyên giảm cân, tăng cơ. Chia sẻ kiến thức miễn phí!',
    subscribers: 890000,
    totalViews: 78000000,
    category: 'fitness',
    isVerified: true,
    socialLinks: [{ platform: 'instagram', url: '#' }],
  },
];

export const VLOG_POSTS: VlogPost[] = [
  {
    id: 'v1',
    slug: 'japan-sakura-2025',
    title: '7 ngày ở Nhật mùa hoa anh đào 2025 — Chi phí thực & Những trải nghiệm không thể quên',
    description: 'Budget 20 triệu cho 7 ngày Nhật Bản: Tokyo, Kyoto, Osaka. Xem hoa anh đào, ăn sushi chuẩn vị, ngủ khách sạn nhộng. KHÔNG CẮT XÉN!',
    thumbnail: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '24:35',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Nhật Bản', 'Du lịch', 'Hoa anh đào', 'Tự túc'],
    views: 2840000,
    likes: 142000,
    comments: 8940,
    publishedAt: '2025-04-10T08:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v2',
    slug: 'pho-ha-noi-authentic',
    title: 'Bí quyết nấu Phở Hà Nội đúng vị — Nước dùng trong veo, thơm ngào ngạt',
    description: 'Công thức phở Hà Nội gia truyền 3 đời. Từ cách chọn xương, nướng gừng hành đến nêm nếm nước mắm. Video chi tiết dài 30 phút cực kỳ tâm huyết.',
    thumbnail: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '31:22',
    creator: CREATORS[1],
    category: 'food',
    tags: ['Phở', 'Nấu ăn', 'Hà Nội', 'Ẩm thực Việt'],
    views: 5600000,
    likes: 280000,
    comments: 22400,
    publishedAt: '2025-06-15T10:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v3',
    slug: 'iphone-16-pro-review-viet',
    title: 'iPhone 16 Pro Max Review sau 3 tháng dùng thật — Đáng tiền không?',
    description: 'Không phải review nhanh 1 tuần. Trải nghiệm thực tế iPhone 16 Pro Max sau 3 tháng làm máy chính: camera, pin, chip A18 Pro và nhiệt độ.',
    thumbnail: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '18:45',
    creator: CREATORS[2],
    category: 'tech',
    tags: ['iPhone', 'Apple', 'Review', 'Smartphone'],
    views: 1240000,
    likes: 62000,
    comments: 4800,
    publishedAt: '2025-06-20T09:00:00Z',
    isTrending: true,
  },
  {
    id: 'v4',
    slug: 'danang-hidden-gems',
    title: 'Đà Nẵng không dành cho khách du lịch — 10 địa điểm người bản địa mới biết',
    description: 'Bỏ qua Cầu Rồng và Bà Nà Hills, mình sẽ đưa bạn đi khám phá những góc yên bình và quán ăn ngon chỉ người Đà Nẵng mới hay ghé.',
    thumbnail: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '20:10',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Đà Nẵng', 'Du lịch', 'Local guide'],
    views: 890000,
    likes: 44500,
    comments: 3200,
    publishedAt: '2025-06-25T07:00:00Z',
  },
  {
    id: 'v5',
    slug: 'banh-mi-saigon-secrets',
    title: 'Hành trình tìm Bánh Mì ngon nhất Sài Gòn — Review 20 tiệm trong 2 ngày',
    description: 'Ăn thử liên tục 20 ổ bánh mì nổi tiếng trong 2 ngày để tìm ra hương vị xuất sắc nhất Sài Gòn. Đánh giá công tâm dựa trên vỏ, pate và bơ!',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '27:18',
    creator: CREATORS[1],
    category: 'food',
    tags: ['Bánh mì', 'Sài Gòn', 'Street food', 'Ăn sập'],
    views: 3200000,
    likes: 160000,
    comments: 12800,
    publishedAt: '2025-06-28T11:00:00Z',
    isTrending: true,
  },
  {
    id: 'v6',
    slug: 'macbook-m4-vs-windows',
    title: 'MacBook M4 Pro vs Windows Gaming Laptop — Cái nào đáng mua cho dân làm việc?',
    description: 'So sánh chi tiết cho nhu cầu công việc thực tế tại Việt Nam. MacBook M4 Pro 60 triệu vs Gaming Laptop 35 triệu về hiệu năng, pin và màn hình.',
    thumbnail: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '22:55',
    creator: CREATORS[2],
    category: 'tech',
    tags: ['MacBook', 'Laptop', 'So sánh', 'Tư vấn'],
    views: 780000,
    likes: 39000,
    comments: 5600,
    publishedAt: '2025-06-30T08:00:00Z',
  },
  {
    id: 'v7',
    slug: 'skincare-routine-viet-6-buoc',
    title: 'Skincare Routine 6 bước cho da Việt — Sạch mụn sau 30 ngày',
    description: 'Quy trình dưỡng da khoa học phù hợp với khí hậu nóng ẩm tại Việt Nam. Sử dụng các sản phẩm lành tính, dễ tìm.',
    thumbnail: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '19:42',
    creator: CREATORS[3],
    category: 'beauty',
    tags: ['Skincare', 'Làm đẹp', 'Trị mụn', 'Dưỡng da'],
    views: 2100000,
    likes: 105000,
    comments: 9200,
    publishedAt: '2025-07-01T08:00:00Z',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'v8',
    slug: 'dau-tu-chung-khoan-tuoi-25',
    title: 'Bắt đầu đầu tư chứng khoán từ tuổi 25 — 5 năm sau kết quả thế nào?',
    description: 'Chia sẻ hành trình đầu tư chứng khoán thực tế từ số vốn nhỏ ban đầu cho đến khi sở hữu danh mục đầu tư tích lũy vững chắc.',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '33:12',
    creator: CREATORS[4],
    category: 'finance',
    tags: ['Đầu tư', 'Chứng khoán', 'Tài chính cá nhân', 'Tích lũy'],
    views: 4500000,
    likes: 225000,
    comments: 18600,
    publishedAt: '2025-07-02T07:00:00Z',
    isTrending: true,
  },
  {
    id: 'v9',
    slug: 'gym-nguoi-moi-bat-dau',
    title: 'Gym cho người mới bắt đầu — Lịch tập 5 ngày/tuần tăng cơ giảm mỡ hiệu quả',
    description: 'Hướng dẫn tập chi tiết cho người mới. Kỹ thuật động tác chuẩn xác, cách phân bổ lịch tập không cần PT.',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '28:06',
    creator: CREATORS[5],
    category: 'fitness',
    tags: ['Gym', 'Tập luyện', 'Tăng cơ', 'Sức khỏe'],
    views: 1800000,
    likes: 90000,
    comments: 7400,
    publishedAt: '2025-07-03T09:00:00Z',
  },
  {
    id: 'v10',
    slug: 'sapa-4-mua-trong-1-ngay',
    title: 'Sapa 4 mùa trong 1 ngày — Trải nghiệm săn mây trên đỉnh Fansipan',
    description: 'Chuyến đi săn mây đầy cảm xúc tại nóc nhà Đông Dương. Cảnh sắc thiên nhiên hùng vĩ đổi thay kỳ diệu qua từng khung giờ.',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '16:30',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Sapa', 'Fansipan', 'Săn mây', 'Tây Bắc'],
    views: 1560000,
    likes: 78000,
    comments: 5100,
    publishedAt: '2025-07-04T06:00:00Z',
  },
  {
    id: 'v11',
    slug: 'make-up-co-gau-style',
    title: 'Trang điểm phong cách trong trẻo nhẹ nhàng đi học đi làm trong 10 phút',
    description: 'Hướng dẫn makeup tối giản, tự nhiên giúp tôn lên đường nét khuôn mặt cực nhanh cho buổi sáng bận rộn.',
    thumbnail: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '14:22',
    creator: CREATORS[3],
    category: 'beauty',
    tags: ['Makeup', 'Tự nhiên', 'Hằng ngày'],
    views: 3400000,
    likes: 170000,
    comments: 14500,
    publishedAt: '2025-07-05T10:00:00Z',
    isTrending: true,
  },
  {
    id: 'v12',
    slug: 'bitcoin-crypto-viet-nam-2025',
    title: 'Bitcoin & Thị trường Crypto tại Việt Nam 2025 — Những điều cần lưu ý',
    description: 'Phân tích tổng quan và các quy định pháp lý mới nhất cần biết trước khi tham gia thị trường tiền mã hóa.',
    thumbnail: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '41:08',
    creator: CREATORS[4],
    category: 'finance',
    tags: ['Bitcoin', 'Crypto', 'Đầu tư'],
    views: 6200000,
    likes: 310000,
    comments: 28000,
    publishedAt: '2025-07-06T07:00:00Z',
    isTrending: true,
  },
  {
    id: 'v13',
    slug: 'chay-bo-marathon-tu-zero',
    title: 'Từ con số 0 đến hoàn thành thử thách chạy Marathon 42km',
    description: 'Hành trình kiên trì tập luyện, vượt qua giới hạn bản thân để chinh phục cự ly chạy bộ dài nhất.',
    thumbnail: 'https://images.unsplash.com/photo-1461897104016-0b3b00cc81ee?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '35:50',
    creator: CREATORS[5],
    category: 'fitness',
    tags: ['Marathon', 'Chạy bộ', 'Nghị lực'],
    views: 920000,
    likes: 46000,
    comments: 3800,
    publishedAt: '2025-07-07T06:30:00Z',
  },
  {
    id: 'v14',
    slug: 'mui-ne-phan-thiet-5-trieu',
    title: 'Du lịch Mũi Né - Phan Thiết 3 ngày 2 đêm chỉ với 5 triệu đồng',
    description: 'Lịch trình ăn chơi thả ga, nghỉ ngơi thoải mái tại thiên đường resort biển Bình Thuận cực kỳ tiết kiệm.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '23:15',
    creator: CREATORS[0],
    category: 'travel',
    tags: ['Mũi Né', 'Phan Thiết', 'Biển', 'Tiết kiệm'],
    views: 2100000,
    likes: 105000,
    comments: 8900,
    publishedAt: '2025-07-08T08:00:00Z',
  },
];

export const TRENDING_POSTS = VLOG_POSTS.filter(p => p.isTrending);
export const FEATURED_POST = VLOG_POSTS.find(p => p.isFeatured) || VLOG_POSTS[0];

export const PLAYLISTS = [
  {
    id: 'pl1',
    title: 'Du lịch Đông Nam Á',
    description: 'Hành trình khám phá các quốc gia Đông Nam Á với chi phí tối ưu nhất.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    creator: CREATORS[0],
    videoCount: 8,
    totalViews: 12000000,
  },
  {
    id: 'pl2',
    title: 'Nấu ăn Việt Nam trọn vị',
    description: 'Tuyển tập hơn 50 video hướng dẫn chế biến các món ăn truyền thống gia đình.',
    thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    creator: CREATORS[1],
    videoCount: 52,
    totalViews: 45000000,
  },
  {
    id: 'pl3',
    title: 'Tech Review 2025',
    description: 'Đánh giá chi tiết các thiết bị công nghệ mới nhất vừa ra mắt trên thị trường.',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
    creator: CREATORS[2],
    videoCount: 24,
    totalViews: 8500000,
  },
  {
    id: 'pl4',
    title: 'Đầu tư thông minh',
    description: 'Kiến thức nền tảng và phương pháp phân bổ tài sản hiệu quả cho người trẻ.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    creator: CREATORS[4],
    videoCount: 18,
    totalViews: 22000000,
  },
];
